## <b>Bi-Gram Language Model</b>


In this notebook, we will try to create a "Bi-Gram" Model

In [2]:
'''
Text taken into consideration : The Adventures of Sherlock Holms (Project Gutenberg)

LINK : https://www.gutenberg.org/ebooks/1661
'''

'\nText taken into consideration : The Adventures of Sherlock Holms (Project Gutenberg)\n\nLINK : https://www.gutenberg.org/ebooks/1661\n'

In [1]:
# Switching from CPU to GPU

import torch
import torch.nn as nn
from torch.nn import functional as F


device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

'''
We better not train the model using CPU, because CPU takes instructions and process them sequentially.
If we need to consider a huge amount of data (text), it will take a long time for the CPU to process 👻

When considering GPUs, they work parallely
'''

cuda


'\nWe better not train the model using CPU, because CPU takes instructions and process them sequentially.\nIf we need to consider a huge amount of data (text), it will take a long for the CPU to process 👻\n\nWhen considering GPUs, they work parallely\n'

In [3]:
# Opening the text file (the book)

with open("SherlockHolms.txt", "r", encoding = 'utf-8') as f: # Character encoding = 'utf-8'
    text = f.read()

print(len(text))

562465


In [4]:
print(text[:200])

Title: The Adventures of Sherlock Holmes

Author: Arthur Conan Doyle

Release date: March 1, 1999 [eBook #1661]
                Most recently updated: October 10, 2023

Language: English

Credits: an


In [5]:
# Making a vocabulary set (of unique characters)

chars = sorted(set(text))
print(chars)
vocab_size = len(chars)

['\n', ' ', '!', '#', '&', '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '£', '½', 'à', 'â', 'æ', 'è', 'é', 'œ', '—', '‘', '’', '“', '”', '\ufeff']


In [6]:
# Encoder - encoding every character shown above by assigning it a unique number

# Number of unique characters above
print(len(chars))

92


In [7]:
# Encode - Decode

string_to_int = {ch:i for i,ch in enumerate(chars)} # Dictionary of encoded character values
int_to_string = {i:ch for i,ch in enumerate(chars)} # Dictionary of decoded character values

encode = lambda s : [string_to_int[c] for c in s]
decode = lambda l : ''.join([int_to_string[i] for i in l])

# Encoding
encoded_hello = encode("hello")
print(encoded_hello)

[59, 56, 63, 63, 66]


In [8]:
# Decoding
decoded_hello = decode([59, 56, 63, 63, 66])
print(decoded_hello)

hello


In [9]:
'''
Tokenization can happen at word level and can also be at the character level.
If it's gonna be at the character level, the vocabulary can be humungous !!!
'''

"\nTokenization can happen at word level and can also be at the character level.\nIf it's gonna be at the character level, the vocabulary can be humungous !!!\n"

In [10]:
# Lets do the above using tensors - pytorch
'''
Put everything what we saw above inside tensors - so that pytorch can easily work with them
'''

'\nPut everything what we saw above inside tensors - so that pytorch can easily work with them\n'

In [11]:
# Putting the encoding function and the data inside the tensor where the datatype inside the
# tensor will be a sequence of super long integers

data = torch.tensor(encode(text), dtype = torch.long)
print(data[:100])

tensor([91, 42, 60, 71, 63, 56, 20,  1, 42, 59, 56,  1, 23, 55, 73, 56, 65, 71,
        72, 69, 56, 70,  1, 66, 57,  1, 41, 59, 56, 69, 63, 66, 54, 62,  1, 30,
        66, 63, 64, 56, 70,  0,  0, 23, 72, 71, 59, 66, 69, 20,  1, 23, 69, 71,
        59, 72, 69,  1, 25, 66, 65, 52, 65,  1, 26, 66, 76, 63, 56,  0,  0, 40,
        56, 63, 56, 52, 70, 56,  1, 55, 52, 71, 56, 20,  1, 35, 52, 69, 54, 59,
         1, 11,  7,  1, 11, 19, 19, 19,  1, 49])


In [12]:
'''
Tensors are similar to Numpy Arrays, but just a different data structure in the context of PyTorch
'''

'\nTensors are similar to Numpy Arrays, but just a different data structure in the context of PyTorch\n'

In [13]:
'''
Validaton and Training Splits
'''

n = int(0.8*len(data)) # Training Data Size
train_data = data[:n]
val_data = data[n:]

# Block size
block_size = 8

# How many blocks we need to get processed in parallel
batch_size = 4

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix)
    X = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    X, y = X.to(device), y.to(device) # Putting the data components in currently selected device (here, GPU)
    return X, y

X, y = get_batch('train')
print('inputs : ')
print(X)
print("\n")
print('target : ')
print(y)

inputs : 
tensor([[ 9, 90,  0,  0, 89, 44, 56, 69],
        [29, 66, 55,  0, 59, 56, 63, 67],
        [70,  1, 59, 56, 52, 55,  1, 70],
        [ 1, 57, 52, 60, 65, 71,  1, 69]], device='cuda:0')


target : 
tensor([[90,  0,  0, 89, 44, 56, 69, 76],
        [66, 55,  0, 59, 56, 63, 67,  1],
        [ 1, 59, 56, 52, 55,  1, 70, 72],
        [57, 52, 60, 65, 71,  1, 69, 60]], device='cuda:0')


In [14]:
'''
Say for the block size = 4, we can understand the below

Say, that the word "hello" can be represented in the below numerical array format🔻
text = [5 16 89 66 34]

Then, when iterating for training, validation and testing - the (X) components can be done : text[:block_size], and (y) can be text[1:block_size+1]
In this way the bi-gram model will understand and learn what can be next probable character in the text
'''

X = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = X[:t+1]
    target = y[t]
    print("When Input is", context, "--> Target is : ", target)

When Input is tensor([91]) --> Target is :  tensor(42)
When Input is tensor([91, 42]) --> Target is :  tensor(60)
When Input is tensor([91, 42, 60]) --> Target is :  tensor(71)
When Input is tensor([91, 42, 60, 71]) --> Target is :  tensor(63)
When Input is tensor([91, 42, 60, 71, 63]) --> Target is :  tensor(56)
When Input is tensor([91, 42, 60, 71, 63, 56]) --> Target is :  tensor(20)
When Input is tensor([91, 42, 60, 71, 63, 56, 20]) --> Target is :  tensor(1)
When Input is tensor([91, 42, 60, 71, 63, 56, 20,  1]) --> Target is :  tensor(42)


In [15]:
'''
For estimating the loss
'''

@torch.no_grad # This decorator makes sure that PyTorch never uses "gradience" at all (HERE)
def estimate_loss():
    out = {}
    model.eval() # Model put to evaluation mode
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, y = get_batch(split)
            logits, loss = model(X, y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train() # Model put to trainig mode
    return out

In [16]:
'''
Creating the Bi-Gram Language Model
'''

class BiGramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) # Embedding Matrix (vocab_size X vocab_size)

    def forward(self, index, targets=None):
        logits = self.token_embedding_table(index) # logits is 3-dimensional

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C) # logits.view(a, b) ==> a = batch size ; b = no. of classes
            targets = targets.view(B*T) # targets.view(a) ==> a = no. of classes
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, index, max_new_tokens):
        # index is (B, T) array of indices in the current context

        '''
        B (Batch Size) : Number of sequences or data samples processed in parallel.
        T (Time-Step/Sequence) : Number of time steps (or sequence length) for each input sample.
        C (Channels) : Number of features or channels for each time step (such as the depth or dimensionality of the input at each time step).
        '''

        for _ in range (max_new_tokens):
            # getting the predictions
            logits, loss = self.forward(index)
            # focussing only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # Applying Softmax to get probabilities
            probs = F.softmax(logits, dim = -1) # (B, C) ==> dim = -1 (as we are focussing on the last dimension)
            index_next = torch.multinomial(probs, num_samples = 1) # (B, 1)
            # Append sampled index to the running sequence
            index = torch.cat((index, index_next), dim = 1) # (B, T+1)
        return index
    

model = BiGramLanguageModel(vocab_size)
m = model.to(device)

context = torch.zeros((1,1), dtype = torch.long, device=device) # torch.long ==> int64
generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)


éœo9½F3)yBur5Y(mbiMn[V;WW?qR“-YVU9.Zf-Zk”D#9e3àmPkdèfH??fv?3rUiIHGo4itSU8IPWBJ—c9AF‘àw9yYZ—u-Zo?S 99½7BæâO!SLtKB,gNAxèBœ5âg2Q4_Dvèh½£Sb1cL5ho]qZfRj-‘lQnk!.jHPUOKU£g:-qwàéa,”G[?2Q—àâtT7‘lPI&OB”fn(fy7‘iVânOLhwq?6Dx
X&£‘æx5Jœq;H]W;8Te’]fv2rè2x;x[8dtw4CmP qLà.p!6j5iq?WClQ9va&Y_“q751:Wæ:oYæVU8C6œæ4i‘iH,EKN“Y:LzsasmppRM443Bv)NVâpBàG[;UbVF4;A6Q—lmX7‘GhW#iæI2VE4ur—;T)½u’.zRjJ zUEqfRX :]vFI[uZâ_oCQk:;&uZâFI6DèTBoLUcILd(B’p—àuAc£”fvaJI”GuUor5Ex½biixSunOzQak25X½æ“PW#—”vV½hp?c9hF;
eJ’MG([eEwuvoE4æG#âBJâ


In [17]:
# Creating a PyTorch Optimzier

learning_rate = 1e-2
max_iters = 10000 # No. of iterations happening in every loop
eval_iters = 250 # For every 250 iteration - it will print the generated text (at that instance)
# dropout = 0.2

optimizer = torch.optim.AdamW(model.parameters(), lr = learning_rate)

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"Step : {iter} ==> Training Loss : {losses['train']:.4f}, Validation Loss : {losses['val']:.4f}")

    # Sampling a batch of data
    Xb, yb = get_batch('train')

    # Evaluating the loss
    logits, loss = model.forward(Xb, yb)
    optimizer.zero_grad(set_to_none = True) # The previous gradience shall not affect the current one
    loss.backward() # Backward Pass
    optimizer.step()
print(loss.item())

Step : 0 ==> Training Loss : 4.8555, Validation Loss : 4.8523
Step : 250 ==> Training Loss : 3.3423, Validation Loss : 3.3216
Step : 500 ==> Training Loss : 2.8133, Validation Loss : 2.7989
Step : 750 ==> Training Loss : 2.6689, Validation Loss : 2.6597
Step : 1000 ==> Training Loss : 2.5556, Validation Loss : 2.5480
Step : 1250 ==> Training Loss : 2.5110, Validation Loss : 2.5025
Step : 1500 ==> Training Loss : 2.5232, Validation Loss : 2.4930
Step : 1750 ==> Training Loss : 2.5145, Validation Loss : 2.4732
Step : 2000 ==> Training Loss : 2.5063, Validation Loss : 2.4590
Step : 2250 ==> Training Loss : 2.4941, Validation Loss : 2.4593
Step : 2500 ==> Training Loss : 2.4851, Validation Loss : 2.4491
Step : 2750 ==> Training Loss : 2.4431, Validation Loss : 2.4296
Step : 3000 ==> Training Loss : 2.4799, Validation Loss : 2.4439
Step : 3250 ==> Training Loss : 2.4506, Validation Loss : 2.4458
Step : 3500 ==> Training Loss : 2.4469, Validation Loss : 2.4261
Step : 3750 ==> Training Loss :

In [18]:
# Generating based on the LOSS shown above

context = torch.zeros((1,1), dtype = torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens = 500)[0].tolist())
print(generated_chars)


s myaliskniof fo Itheenobve Be ifethe hod witond the sthicold,

Thang at t, athe ft l atoman an the r a sint ookioomuseriod ghithair orchter Frertoson, be wid gesinisthrepoocod s s oibe ide y stre ombond s s ys
Nowe malmeaslest l’tofot t. msl har ie then blenive,
thayo quth whensend an nct, e,
ned holfinshye. brs fire je yea it o. poumy anfa whe
herind tiodkexarhipatha oweisthevinilaw te.” d an e abll the
canthoucksorascaver f ik-rotat atrey weistiest d winge I ligherd as ilerecharimes. win blli


In [19]:
'''
For learning more about PyTorch Optimizers🔽

https://pytorch.org/docs/stable/optim.html
'''

'\nFor learning more about PyTorch Optimizers🔽\n\nhttps://pytorch.org/docs/stable/optim.html\n'