# <b>PyTorch - Examples (Basic Functions Usage)</b>

<br>
<br>

In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,)) # tensor of 6 random integers between -100 and 100
print(randint)

tensor([ 64,  14, -49,  77, -60, -89])


In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.5, 9.8], [8.6, 9.1]]) # Matrix of dimension --> 3 X 2
print(tensor)

tensor([[0.1000, 1.2000],
        [2.5000, 9.8000],
        [8.6000, 9.1000]])


In [4]:
zeros = torch.zeros(2, 3) # Tensor --> 2 X 3 Matrix of Zeroes (floating point numbers)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
ones = torch.ones(6, 3) # Tensor --> 6 X 3 Matrix of Ones (floating point numbers)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [6]:
input = torch.empty((2,3), dtype=torch.float64) # Returns a tensor filled with uninitialized data.
input

tensor([[1.4860e-311,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.float64)

In [7]:
arange = torch.arange(5) # Tensor --> array of integer values (0 to 5-1)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3, 10, steps = 5) # Tensor --> 5 equidistant floating point numbers between 3 and 10 (inclusive)
print(linspace)

'''
You can also write the above code as below 🔻
linspace = torch.linspace(start = 3, end = 10, steps = 5) 
'''

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])


'\nYou can also write the above code as below 🔻\nlinspace = torch.linspace(start = 3, end = 10, steps = 5) \n'

In [11]:
logspace = torch.logspace(start=-10, end=10, steps = 5) # Tensor --> 5 terms with e**(start) to e**(end) (all inclusive) - all power terms equidistant
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [13]:
eye = torch.eye(5) # Tensor Matrix --> 5 X 5 matrix full of zeroes (with only the main diagonal filled with ones)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

# Empty Tensor Matrix of order 2X3 (full of zeroes)

tensor([[0, 0, 0],
        [0, 0, 0]])